import React from 'react'
import { useFarmStore } from './state/farmStore'
import { Check } from 'lucide-react'

// Domain Features
import FarmProfileForm from './features/farm-profile/FarmProfileForm'
import CropDecision from './features/crop-decision/CropDecision'
import SoilCorrections from './features/soil-preparation/SoilCorrections'
import Financials from './features/financial-plan/Financials'
import PestDefense from './features/pest-defense/PestDefense'
import PrintableActionPlan from './features/action-plan/PrintableActionPlan'
import FarmAdvisor from './features/ai-advisor/FarmAdvisor'

const STAGES = [
  { id: 'farm-profile', label: 'Soil Data' },
  { id: 'recommendations', label: 'Crop Match' },
  { id: 'soil-corrections', label: 'Soil Fix' },
  { id: 'financials', label: 'Profit' },
  { id: 'pests', label: 'Pest Risk' },
  { id: 'action-plan', label: 'Action Plan' }
] as const

function App() {
  const { stage, setStage, profile, selectedCrop } = useFarmStore()

  const currentStageIndex = STAGES.findIndex(s => s.id === stage)

  const renderStage = () => {
    switch (stage) {
      case 'farm-profile':
        return <FarmProfileForm />
      case 'recommendations':
        return <CropDecision />
      case 'soil-corrections':
        return <SoilCorrections />
      case 'financials':
        return <Financials />
      case 'pests':
        return <PestDefense />
      case 'action-plan':
        return <PrintableActionPlan />
      default:
        return <FarmProfileForm />
    }
  }

  // Navigation guards
  const handleStepClick = (idx: number, targetStageId: typeof STAGES[number]['id']) => {
    if (idx > currentStageIndex) {
      // Trying to jump forward
      if (idx > 0 && !profile) return // Need profile for anything past step 0
      if (idx > 1 && !selectedCrop) return // Need crop for anything past step 1
    }
    setStage(targetStageId)
  }

  return (
    <div className="app-container">
      <header className="app-header">
        <img
          className="app-logo"
          src="/thulir-logo.png"
          alt="Thulir logo"
        />
        <div>
          <h1 style={{ fontSize: '24px' }}><span className="gradient-text">Thulir</span></h1>
          <p style={{ fontSize: '14px', color: 'var(--muted-foreground)', fontFamily: 'var(--font-mono)' }}>FARM DECISION SUPPORT</p>
        </div>
      </header>

      <div className="progress-stepper">
        {STAGES.map((s, idx) => {
          const isActive = stage === s.id
          const isCompleted = idx < currentStageIndex
          
          let statusClass = ''
          if (isActive) statusClass = 'active'
          else if (isCompleted) statusClass = 'completed'

          return (
            <div 
              key={s.id} 
              className={`step-item ${statusClass}`}
              onClick={() => handleStepClick(idx, s.id)}
              style={{ cursor: (idx <= currentStageIndex || (idx === 1 && profile) || (idx > 1 && selectedCrop)) ? 'pointer' : 'default' }}
            >
              <div className="step-number">
                {isCompleted ? <Check size={14} /> : (idx + 1)}
              </div>
              <span>{s.label}</span>
            </div>
          )
        })}
      </div>

      <main className="main-content">
        {renderStage()}
        {stage !== 'farm-profile' && <FarmAdvisor />}
      </main>

      {/* Persistent Disclaimer */}
      <footer className="disclaimer-banner texture-dots print-hide">
        ⚠️ THULIR DEMONSTRATION ONLY. 
        Recommendations are generated by Thulir decision-support models. Confirm major cultivation, crop-protection, and financial decisions with a certified agronomist or local KVK extension officer.
      </footer>
    </div>
  )
}

export default App
